# Site settings
title: Jekyll Crisp Theme
author: David Zhang
description: "Minimalism theme of Jekyll from Crisp"
encoding: utf-8
markdown: kramdown
baseurl: /jekyll-crisp-theme
# Menu
menu:
  - archive.md
  - project.md
  - about.md
# Contact Icons
contact:
  - link: mailto:yourmail@example.com
    icon: fa-envelope-o
  - link: https://github.com/crispgm/jekyll-crisp-theme
    icon: fa-github
  - link: https://twitter.com/crispgm
    icon: fa-twitter
# GitHub Repo for your site
issue_report:
  github: crispgm/jekyll-crisp-theme
# Google Analytics
google_analytics: UA-50708664-1
# Disqus
disqus:
  shortname: crispgm
# Exclusion
exclude:
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - jekyll-crisp-minimal-theme.gemspec
  - screenshot.jpg
  - /docs
